# Este é um fluxo de trabalho básico para ajudá-lo a começar com Actions

name: CI

# Controla quando o fluxo de trabalho será executado
on:
  # Dispara o fluxo de trabalho em eventos de push ou pull request, mas apenas para o ramo "develop"
  push:
    branches: [ "develop" ]

  # Permite executar este fluxo de trabalho manualmente na guia Actions
  workflow_dispatch:

# Uma execução de fluxo de trabalho é composta por um ou mais jobs que podem ser executados sequencialmente ou em paralelo
jobs:
  # Este fluxo de trabalho contém um único job chamado "build"
  build:
    # O tipo de runner que o job será executado
    runs-on: ubuntu-latest

    # As etapas representam uma sequência de tarefas que serão executadas como parte do job
    steps:
      # Verifica o seu repositório sob $GITHUB_WORKSPACE, para que seu job possa acessá-lo
      - uses: actions/checkout@v4

      
      - name: Instalar dependências
        run: npm install

      - name: Executar Jest
        run: npm test
